server:
  port: 9999
spring:
  application:
    name: fit-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fit-auth
          uri:
            lb://fit-auth
          predicates:
            - Path=/auth/**
          filters:
            - ValidateCodeGatewayFilter
            - PasswordDecoderFilter
        - id: fit-admin
          uri:
            lb://fit-admin
          predicates:
            - Path=/admin/**
        - id: openapi
          uri:
            lb://fit-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
gateway:
  encode-key: 'thanks,pig4cloud'
  ignore-clients:
    - test
    - client
    - client1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always