spring:
  application:
    name: fit-generator
  datasource:
    password: admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fit?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000