spring:
  profiles:
    active: dev
  application:
    name: fit-auth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
      discovery:
        server-addr: http://localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fit?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
  main:
    allow-circular-references: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 3000
  ssl:
    enabled: false
logging:
  level:
    root: debug
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic